### ISSUE TITLE
Edit link blank page

### ISSUE THREAD

**Issue by fourroses666** [mnoskov/commerce-dashboard#4]
![link](https://user-images.githubusercontent.com/523389/52551871-8a6e8800-2dde-11e9-9c37-c1f6200a87d4.png)

Edit link shows a blank page. Is it something you want to build-in in the future to edit the orders?
Add / remove products or change prices etc.?
/#?a=112&id=4&route=orders/edit&order_id=x

We can only edit the state (new/canceled) if I'm right.

**Comment by mnoskov** [comment]
Yes, you're right, it is in developing now.

**Comment by fourroses666** [comment]
Oke cool.
