### ISSUE TITLE
After install not showing on Dashboard

### ISSUE THREAD

**Issue by fourroses666** [mnoskov/commerce-dashboard#5]
Replace on line 3:

`if (!empty($modx->commerce)) {`

to

`if (defined('COMMERCE_INITIALIZED')) {`

**Comment by fourroses666** [comment]
This also works; (CommerceOptions uses this)
`if (empty($modx->commerce) || !defined('COMMERCE_INITIALIZED')) {`

**Comment by mnoskov** [comment]
https://github.com/mnoskov/commerce-dashboard/commit/ac587fe57b9816a059f98444113cb4fcf33b3237
